# Generated by Django 4.1.1 on 2022-10-14 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='middle_name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
