# Generated by Django 4.1.1 on 2022-10-27 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_school_management', '0002_remove_classroom_parents_remove_classroom_teachers_and_more'),
        ('account', '0002_remove_parent_child_name_teacher_classrooms_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='classrooms',
            field=models.ManyToManyField(blank=True, to='admin_school_management.classroom'),
        ),
    ]
