# Generated by Django 4.1.1 on 2022-10-27 07:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_teacher_classrooms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='first_name',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(message='Please enter a valid first name. Minimum 2 and maximum 64 alphabets allowed.', regex='^[a-zA-Z]{2,64}$')]),
        ),
        migrations.AlterField(
            model_name='child',
            name='last_name',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(message='Please enter a valid first name. Minimum 2 and maximum 64 alphabets allowed.', regex='^[a-zA-Z]{2,64}$')]),
        ),
        migrations.AlterField(
            model_name='child',
            name='middle_name',
            field=models.CharField(blank=True, max_length=255, null=True, validators=[django.core.validators.RegexValidator(message='Please enter a valid first name. Minimum 2 and maximum 64 alphabets allowed.', regex='^[a-zA-Z]{2,64}$')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(message='Please enter a valid first name. Minimum 2 and maximum 64 alphabets allowed.', regex='^[a-zA-Z]{2,64}$')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(message='Please enter a valid first name. Minimum 2 and maximum 64 alphabets allowed.', regex='^[a-zA-Z]{2,64}$')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='middle_name',
            field=models.CharField(blank=True, max_length=255, null=True, validators=[django.core.validators.RegexValidator(message='Please enter a valid first name. Minimum 2 and maximum 64 alphabets allowed.', regex='^[a-zA-Z]{2,64}$')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.IntegerField(blank=True, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Please enter a valid phone number. Digits length should be 10.', regex='^[0-9]{10}$')]),
        ),
    ]
