# Generated by Django 4.1.1 on 2022-10-27 23:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_child_first_name_alter_child_last_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='student_id',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Please enter a valid id. Maximum 64 alphabets and digits allowed.', regex='^[a-zA-Z0-9]{0,30}$')]),
        ),
        migrations.AlterField(
            model_name='researcher',
            name='researcher_id',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Please enter a valid id. Maximum 64 alphabets and digits allowed.', regex='^[a-zA-Z0-9]{0,30}$')]),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='teacher_id',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Please enter a valid id. Maximum 64 alphabets and digits allowed.', regex='^[a-zA-Z0-9]{0,30}$')]),
        ),
    ]
