# Generated by Django 4.1.1 on 2022-10-28 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_school_management', '0005_alter_classroom_school'),
        ('account', '0007_alter_child_student_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='classroom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_school_management.classroom'),
        ),
        migrations.AlterField(
            model_name='child',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.parent'),
        ),
        migrations.AlterField(
            model_name='child',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_school_management.school'),
        ),
    ]
