# Generated by Django 4.1.1 on 2022-10-28 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_school_management', '0005_alter_classroom_school'),
        ('account', '0008_alter_child_classroom_alter_child_parent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_school_management.school'),
        ),
    ]
