# Generated by Django 4.1.1 on 2022-10-16 00:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('school_id', models.CharField(max_length=100, unique=True)),
                ('address', models.TextField(blank=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.IntegerField(blank=True, null=True, unique=True)),
                ('teachers', models.ManyToManyField(to='account.teacher')),
            ],
            options={
                'verbose_name_plural': 'schools',
                'ordering': ['school_id'],
            },
        ),
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('class_id', models.CharField(max_length=100, unique=True)),
                ('parents', models.ManyToManyField(to='account.parent')),
                ('school', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='admin_school_management.school')),
                ('teachers', models.ManyToManyField(to='account.teacher')),
            ],
            options={
                'verbose_name_plural': 'classrooms',
                'ordering': ['class_id'],
            },
        ),
    ]
