# Generated by Django 4.1.1 on 2022-10-10 00:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('classid', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'classrooms',
                'ordering': ['classid'],
            },
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('schoolid', models.IntegerField()),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Classroom', to='admin_school_management.classroom')),
            ],
            options={
                'verbose_name_plural': 'schools',
                'ordering': ['schoolid'],
            },
        ),
    ]
