# Generated by Django 4.1.1 on 2022-10-27 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_school_management', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classroom',
            name='parents',
        ),
        migrations.RemoveField(
            model_name='classroom',
            name='teachers',
        ),
        migrations.RemoveField(
            model_name='school',
            name='teachers',
        ),
    ]
