# Generated by Django 4.1.1 on 2022-10-28 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_school_management', '0004_alter_classroom_class_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_school_management.school'),
        ),
    ]
