# Generated by Django 4.1.1 on 2022-11-11 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('group_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='researchergroup',
            name='researcher',
            field=models.ManyToManyField(related_name='researcher_group', to='account.researcher'),
        ),
    ]
