# Generated by Django 4.1.1 on 2022-11-04 00:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('group_management', '0005_parentgroup_content_type_parentgroup_object_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parentgroup',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='parentgroup',
            name='object_id',
        ),
        migrations.RemoveField(
            model_name='researchergroup',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='researchergroup',
            name='object_id',
        ),
        migrations.RemoveField(
            model_name='teachergroup',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='teachergroup',
            name='object_id',
        ),
        migrations.AddField(
            model_name='parentgroup',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='researchergroup',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='teachergroup',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
